### PR TITLE
Add module "map_block_full_no_vote"

### PR DESCRIPTION
**Pull request by enoldev**

### CODE REVIEW

**Comment by abourget** [comment]
This is the filtering TopLedger does for Solana:

```rust
let meta = match trx.meta.as_ref() {
    Some(meta) => meta,
    None => continue,
};

let transaction = match trx.transaction.as_ref() {
    Some(transaction) => transaction,
    None => continue,
};

let message = transaction.message.as_ref().expect("Message is missing");

// Skip Vote Transactions
if message.account_keys.contains(&decoded_vote_account) {
    continue;
}

// Filter only success txns
if meta.err.is_some() {
    continue;
}
```

**Comment by abourget** [comment]
They also added: 
>Specifically, you should filter out transactions associated with the vote program, identifiable by the program ID Vote111111111111111111111111111111111111111, and the address lookup table program, identifiable by the program ID AddressLookupTab1e1111111111111111111111111.

**Comment by billettc** [comment]
@abourget TopLedger should change there substreams ...
```
// Skip Vote Transactions
if message.account_keys.contains(&decoded_vote_account) {
    continue;
}
```

This should be replace by ...
```
// Skip Vote Transactions
if message.resolved_accounts().contains(&decoded_vote_account) {
    continue;
}
```

`account_keys` is missing all the accounts parts of address lookup ...

_AddressLookupTab1e1111111111111111111111111_ there is not a lot of them and I think they can be useful.
_Vote111111111111111111111111111111111111111_ are we suggesting the remove them from the blocks?

**Comment by abourget** [comment]
Yes for the Vote111.. we want to make them into thinner Blocks.. and most people won't want to filter through them.

**Comment by abourget** [comment]
@billettc because the Vote transactions are built using the `solana-validator` and there's only one account, it might be fair to just look the accounts and not expect it to be in a lookup table.. in which case it would be a non-standard Vote  transactions.. and might want to be checked upon.

**Comment by abourget** [comment]
Ok, gave it a little swing there, and tested. Properly filters out votes.

**Pull request merged**
